name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: npm run build
      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd dist
          git init
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy site from GitHub Actions: ${{ github.sha }}" || echo "No changes to commit"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
      - uses: actions/configure-pages@v4
        with:
          branch: gh-pages
          path: /
